import type { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { USERS, connect, disconnect, selectAs } from './helpers/db';

/**
 * bdoor ID (BI-OS §4.2): a private platform identifier, generated by the
 * database, unique, and readable only through the companies table's existing
 * tenancy — the column must add no new exposure.
 */
let client: Client;

beforeAll(async () => {
  client = await connect();
});

afterAll(async () => {
  await disconnect(client);
});

describe('the bdoor ID column', () => {
  it('is generated for every company, in the private BDR format, uniquely', async () => {
    const { rows } = await client.query<{ bdoor_id: string }>(
      'select bdoor_id from public.companies',
    );
    expect(rows.length).toBeGreaterThan(0);
    const ids = rows.map((row) => row.bdoor_id);
    for (const id of ids) expect(id).toMatch(/^BDR-[0-9A-F]{6}-[0-9A-F]{6}$/);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('is assigned on insert without the application choosing it', async () => {
    await client.query('begin');
    try {
      const { rows } = await client.query<{ bdoor_id: string; opt_in: boolean }>(
        `insert into public.companies (organization_id, legal_name, structure)
         select organization_id, 'BDR Insert Probe (sample)', 'private_limited'
         from public.companies limit 1
         returning bdoor_id, public_verification_opt_in as opt_in`,
      );
      expect(rows[0]?.bdoor_id).toMatch(/^BDR-/);
      // Never public by default: verification is opt-in, and nothing reads
      // the flag yet — the column exists so the future surface starts opt-in.
      expect(rows[0]?.opt_in).toBe(false);
    } finally {
      await client.query('rollback');
    }
  });

  it('stays inside the companies tenancy — a customer sees only their own ids', async () => {
    const own = await selectAs(client, USERS.localFounder, 'select bdoor_id from public.companies');
    const all = await client.query<{ bdoor_id: string }>('select bdoor_id from public.companies');
    expect(own.length).toBeGreaterThan(0);
    // The wrong-actor check: the seed holds companies in more than one
    // organisation, so RLS must leave this member strictly short of the
    // whole table.
    expect(own.length).toBeLessThan(all.rows.length);
    for (const row of own as Array<{ bdoor_id: string }>) {
      expect(row.bdoor_id).toMatch(/^BDR-/);
    }
  });
});
