import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { connect, disconnect } from './helpers/db';

let client: Client;

beforeAll(async () => {
  client = await connect();
});

afterAll(async () => {
  await disconnect(client);
});

const SOURCE = readFileSync(join(process.cwd(), 'src/types/database.ts'), 'utf8');

/** The column names in one table's `Row` block, in declaration order. */
function rowColumns(table: string): string[] {
  const start = SOURCE.indexOf(`      "${table}": {\n        Row: {\n`);
  if (start === -1) throw new Error(`${table} is missing from src/types/database.ts`);
  const body = SOURCE.slice(start);
  const rowBlock = body.slice(body.indexOf('Row: {'), body.indexOf('\n        Insert: {'));
  // Digits belong in the class: requires_aal2 was dropped without them.
  return [...rowBlock.matchAll(/^\s+"([a-z0-9_]+)"\??:/gm)].map((m) => m[1]!);
}

async function actualColumns(table: string): Promise<string[]> {
  const { rows } = await client.query<{ column_name: string }>(
    `select column_name from information_schema.columns
     where table_schema = 'public' and table_name = $1
     order by ordinal_position`,
    [table],
  );
  return rows.map((r) => r.column_name);
}

/**
 * `src/types/database.ts` is generated by `pnpm run db:types`, which needs a
 * running Supabase stack. That is not available everywhere the migrations are,
 * so nothing has been checking that the committed types still describe the
 * schema — a migration can add a column and the types keep compiling against
 * the old shape, which is how a Server Action ends up silently writing nothing.
 *
 * This compares the two directly. It covers the authorization tables rather
 * than all 76: they are the ones added without the generator, so they are the
 * ones with no tool standing behind them.
 */
describe('generated types match the schema', () => {
  const TABLES = [
    'permission_catalog',
    'role_templates',
    'role_template_permissions',
    'role_assignments',
    'membership_permission_overrides',
    'platform_invitations',
  ];

  it.each(TABLES)('%s has the same columns in both', async (table) => {
    expect(rowColumns(table)).toEqual(await actualColumns(table));
  });

  it('declares every table the Data API exposes', async () => {
    // A table with RLS and no entry here cannot be reached from typed code at
    // all, which tends to be discovered late and by accident.
    const { rows } = await client.query<{ table_name: string }>(
      `select table_name from information_schema.tables
       where table_schema = 'public' and table_type = 'BASE TABLE'
       order by 1`,
    );
    const missing = rows
      .map((r) => r.table_name)
      .filter((name) => !SOURCE.includes(`      "${name}": {\n`));
    expect(missing).toEqual([]);
  });
});
